export const WS_ALL_ORDERS_CONNECTION_START = "WS_ALL_ORDERS_CONNECTION_START";
export const WS_ALL_ORDERS_CONNECTION_SUCCESS = "WS_ALL_ORDERS_CONNECTION_SUCCESS";
export const WS_ALL_ORDERS_CONNECTION_ERROR = "WS_ALL_ORDERS_CONNECTION_ERROR";
export const WS_ALL_ORDERS_CONNECTION_CLOSING = "WS_ALL_ORDERS_CONNECTION_CLOSING";
export const WS_ALL_ORDERS_CONNECTION_CLOSED = "WS_ALL_ORDERS_CONNECTION_CLOSED";
export const WS_ALL_ORDERS_GET_ORDER = "WS_ALL_ORDERS_GET_ORDER";

export const wsAllOrdersConnectionStart = () => {
  return {
    type: WS_ALL_ORDERS_CONNECTION_START,
  };
};

export const wsAllOrdersConnectionClosed = () => {
  return {
    type: WS_ALL_ORDERS_CONNECTION_CLOSED,
  };
};

export const wsAllOrdersActions = {
  wsInit: WS_ALL_ORDERS_CONNECTION_START,
  onOpen: WS_ALL_ORDERS_CONNECTION_SUCCESS,
  onClosing: WS_ALL_ORDERS_CONNECTION_CLOSING,
  onClose: WS_ALL_ORDERS_CONNECTION_CLOSED,
  onError: WS_ALL_ORDERS_CONNECTION_ERROR,
  onMessage: WS_ALL_ORDERS_GET_ORDER,
};
